steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
    - --destination=gcr.io/$PROJECT_ID/csi-driver-sdfs-bin:$BRANCH_NAME
    - --cache=true
    - --cache-ttl=10h
    - --dockerfile=Dockerfile.build
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: [ '-c', 'mkdir -p /workspace/bin']
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: [ '-c', 'docker run -v /workspace/bin:/opt/mount --rm --entrypoint cp gcr.io/$PROJECT_ID/csi-driver-sdfs-bin:$BRANCH_NAME /go/csi-driver-sdfs/bin/sdfsplugin /opt/mount/sdfsplugin']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gsutil cp /workspace/bin/sdfsplugin gs://${_DIST_BUCKET}/csi-driver-sdfs/sdfsplugin-$BRANCH_NAME" ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: gcr.io/kaniko-project/executor:latest
  secretEnv: ['USERNAME']
  args:
    - --destination=docker.io/$$USERNAME/csi-driver-sdfs:$BRANCH_NAME
    - --cache=true
    - --cache-ttl=10h
    - --dockerfile=Dockerfile
substitutions:
  _DIST_BUCKET: abucket # default value
timeout: 10800s
options:
  machineType: 'N1_HIGHCPU_8'
availableSecrets:
   secretManager:
   - versionName: projects/$PPROJECT_NUMBER/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/$PROJECT_NUMBER/secrets/docker-username/versions/1
     env: 'USERNAME'
