FROM golang:1.13-alpine

LABEL maintainer="Sam Silverberg  <sam.silverberg@gmail.com>"

ENV GOPATH /go
ENV CGO_ENABLED 0
ENV GO111MODULE on
COPY ./ /go/csi-driver-sdfs

RUN  \
     apk add --no-cache git build-base && \
     cd /go/csi-driver-sdfs && \
     mkdir -p /go/csi-driver-sdfs/bin
WORKDIR  /go/csi-driver-sdfs/
RUN make build