---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deployment-sdfs
spec:
  accessModes:
    - ReadWriteMany  # In this example, multiple Pods consume the same PVC.
  resources:
    requests:
      storage: 10Gi
  storageClassName: sdfs-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment-sdfs
  template:
    metadata:
      name: deployment-sdfs
      labels:
        name: deployment-sdfs
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: deployment-sdfs
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(hostname) $(date) >> /mnt/sdfs/outfile; sleep 1; done
          volumeMounts:
            - name: sdfs
              mountPath: "/mnt/sdfs"
      volumes:
        - name: sdfs
          persistentVolumeClaim:
            claimName: pvc-deployment-sdfs
