---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sdfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: sdfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: "sdfs://sdfs-server.default.svc.cluster.local:6442"
