---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sdfs-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-sdfs
  storageClassName: ""
