---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sdfs-csi
provisioner: sdfs.csi.k8s.io
parameters:
  server: "sdfs://sdfs-server.default.svc.cluster.local:6442"
reclaimPolicy: Delete
volumeBindingMode: Immediate

